-- 2022년 1월의 카테고리 별 도서 판매량을 합산하고, 카테고리(CATEGORY), 
-- 총 판매량(TOTAL_SALES) 리스트를 출력하는 SQL문을 작성해주세요.

SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES 
FROM BOOK AS B 
LEFT JOIN BOOK_SALES AS S
ON B.BOOK_ID = S.BOOK_ID 
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY CATEGORY
ORDER BY B.CATEGORY ASC;